
<h1>Create a new post </h1>

<div class="template">
    <div class="container">
        <form method='POST' action="save">
			<div class="form-group">
				<label for="name">Name</label>
				<input type="text" class="form-control" id="name" placeholder="Name" name="name">
			</div>
            <br>
            <div class="form-group">
				<label for="content">Content</label>
				<input type="text" class="form-control" id="content" placeholder="Content" name="content">
	    	</div>
            <br>
            <button type="submit" class="btn btn-primary" name="btn_create">Submit</button>
        </form>
    </div>

</div>